### ISSUE TITLE
Add a Search component in the AppBar 

### ISSUE THREAD

**Issue by eini-rc** [WolfSeminary/worldwide-library#13]
## Objective

A new `SearchBooks` component should be added to the app bar

## Summary

The search component will allow the user to search for a specific book

## Artifacts

The MUI component that should be used is the [Search](https://mui.com/components/app-bar/#app-bar-with-search-field) component

## Implementation details

1. Within the `AppBar` component add a new `SearchBooks ` component 
2. If the `AppBar` component doesn't exist add a comment in top of the component- `To be added to the <AppBar /> component`
2. Add a `SearchIcon` icon
3. Make sure to include a `Search...` placeholder

## New components

`<SearchBooks />`

## Example

![image](https://user-images.githubusercontent.com/39950157/145689317-07b03ec9-01ed-43f8-8b75-61f92407f4f4.png)

**Comment by orabenesh** [comment]
Close: #13
