### ISSUE TITLE
NoBooks component - Render

### ISSUE THREAD

**Issue by eini-rc** [WolfSeminary/worldwide-library#30]
# Objective
In order to improve the user experience, a "No available books" message should be added when there are no books on the page

# Summary
A `<NoBooks/>` component should be added to improve the user experience

# Artifacts
React [Conditional Rendering](https://reactjs.org/docs/conditional-rendering.html)
# Implementation details

1. Call the `<NoBooks/>` component on the books page, just before the books items
2. Conditionally the render of the `<NoBooks/>` component according to the `books` state, the component should render only when there are no books on the page

**Comment by orabenesh** [comment]
Close: #30
