### ISSUE TITLE
Add a Book Info component

### ISSUE THREAD

**Issue by eini-rc** [WolfSeminary/worldwide-library#7]
## Objective

A new book info component should be added to the BookInfo page

## Summary

The info section should give the user all the info he needs about the book

## Artifacts

The MUI component that should be used is the [card](https://mui.com/components/cards/#media) component

## Implementation details

1. Add a new `BookInfo` component
2. Add a MUI `Card` element to wrap the Info 
2. On the `Card` add a Title:  `Book Info` using the `Typography` element
3. Add a `CardContent` section for the book info
4.Add a `Typography` component for the Title:  `Book Info` 
5. Add the following labels:

      - Title - (`title` prop in google API)
      - Author - (`authors` prop in google API)
      - Publisher - (`publisher` prop in google API)
      - Published Date - (`publishedDate` prop in google API)
      - Description - (`description` prop in google API)
      - Num of Pages - (`pageCount` prop in google API)
      - Language - (`language` prop in google API)

## New components

`<BookInfo />`

## Example

![image](https://user-images.githubusercontent.com/39950157/145689007-5166fe30-0a29-477d-b8c3-1a2bd8d3f73d.png)

**Comment by talBaker39** [comment]
book info merged into master
